[package]
name = "fedidex_web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "^0.19"
serde = "1.0.147"
serde_json = "1.0.87"
web-sys = "0.3.60"
wasm-bindgen = "0.2.83"